
# http://www.appveyor.com/docs/appveyor-yml
version: "1.0{build}"

skip_tags: true

environment:

  matrix:
    # Node versions to run
    - nodejs_version: 8
    - nodejs_version: 7
    - nodejs_version: 6

init:
  - git config --global core.autocrlf input

install:
  - choco install -y googlechrome --ignore-checksums
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\yarn;%PATH%
  - yarn

build: off

test_script:
  # run tests and run build
  - yarn run test
  - yarn run build

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json
