export const CONVERT_CURRENCY_VALUE = 'wallet/Home/Currency/CONVERT_CURRENCY_VALUE';
export const GET_CONVERTED_CRYPTOCURRENCY_TO_BRL = 'wallet/Home/Currency/GET_CONVERTED_CRYPTOCURRENCY_TO_BRL';
export const EXCHANGE_BRL_TO_CRYPTOCURRECY = 'wallet/Home/Currency/EXCHANGE_BRL_TO_CRYPTOCURRECY';

