export const CONVERT_CURRENCY_VALUE = 'wallet/Home/Currency/CONVERT_CURRENCY_VALUE';
export const LIST_AVAILIBLE_CURRENCIES = 'wallet/Home/Currency/LIST_AVAILIBLE_CURRENCIES';
export const AVAILIBLE_CURRENCIES = 'wallet/Home/Currency/AVAILIBLE_CURRENCIES';
export const EXCHANGE_CRYPTOCURRECY = 'wallet/Home/Currency/EXCHANGE_CRYPTOCURRECY';

